export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_SUCCEED = 'AUTHENTICATION_SUCCEED';
export const GET_CURRENT_USERNAME = 'GET_CURRENT_USERNAME';
export const LOGOUT = 'LOGOUT';
export const GET_JOBS_LIST = 'GET_JOBS_LIST';
export const ADD_NEW_JOB = 'ADD_NEW_JOB';
export const ADD_NEW_CANDIDATE = 'ADD_NEW_CANDIDATE';
export const GET_ALL_CANDIDATES = 'GET_ALL_CANDIDATES';
